<a href="https://colab.research.google.com/github/data2450/sentimental-analysis-basics/blob/main/practisce_setimental_analysis_on_movie_review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

count= CountVectorizer()


docs=np.array([ 'The sun is shining',
                'The weather is sweet',
                'The sun is shining, the weather is sweet, and one and one is two'])

**Bag of words**:way to represent text for use in ML ,which ignores the structure and only counts how often each word occure 

**count vectorizer** allows us to use the **bag of words** approach by converting collection of text document into matrix of token count

In [ ]:
#now the text document is inside the array
docs

array(['The sun is shining', 'The weather is sweet',
       'The sun is shining, the weather is sweet, and one and one is two'],
      dtype='<U64')

In [ ]:
bag=count.fit_transform(docs)

In [ ]:
bag

<3x9 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Row format>

# Sparse Matrix
A sparse matrix is a matrix that is comprised of mostly zero values.

Sparse matrices are distinct from matrices with mostly non-zero values, which are referred to as dense matrices.

In [ ]:
print(count.vocabulary_)

{'the': 6, 'sun': 4, 'is': 1, 'shining': 3, 'weather': 8, 'sweet': 5, 'and': 0, 'one': 2, 'two': 7}


In [ ]:
print(bag.toarray())

[[0 1 0 1 1 0 1 0 0]
 [0 1 0 0 0 1 1 0 1]
 [2 3 2 1 1 1 2 1 1]]


the first index is 'and' and if check the first column we can see the first element is zero sine the word 'and' is not present in the first sentance and 2nd sentance , in 3rd sentance "and" is ocurring 2 times so the 3rd value in the column will be 2 

2nd column of the matrix represnt the word "is" present in 1st and 2nd sentance once and 3 times in 3rd sentance

**Task 3: Word relevancy using term frequency-inverse document frequency**



**TF**: Term Frequency, which measures how frequently a term occurs in a document. Since every document is different in length, it is possible that a term would appear much more times in long documents than shorter ones. Thus, the term frequency is often divided by the document length (aka. the total number of terms in the document) as a way of normalization

**TF(t)** = (Number of times term t appears in a document) / (Total number of terms in the document).

**IDF**: Inverse Document Frequency, which measures how important a term is. While computing TF, all terms are considered equally important. However it is known that certain terms, such as "is", "of", and "that", may appear a lot of times but have little importance. Thus we need to weigh down the frequent terms while scale up the rare ones, by computing the following:

**IDF(t)** = log_e(Total number of documents / Number of documents with term t in it).



**TF-IDF** =  **TF * IDF** 

allows as to weight terms based on how important they are to the document .High weight is given to terms that appear often in a particular document .But don't appear ofen in the corpus . features with low tfidf are either commonly used across all documents or rarely used and only occur in long document

In [ ]:
import numpy as np
from sklearn.feature_extraction.text import TfidfTransformer
np.set_printoptions(precision=2)
tfidf=TfidfTransformer(use_idf=True, norm='l2', smooth_idf=True)
print(tfidf.fit_transform(count.fit_transform(docs)).toarray())

[[0.   0.43 0.   0.56 0.56 0.   0.43 0.   0.  ]
 [0.   0.43 0.   0.   0.   0.56 0.43 0.   0.56]
 [0.5  0.45 0.5  0.19 0.19 0.19 0.3  0.25 0.19]]


so we can see that the word "is"  has score 0.43 because the word is occuring in all the sentance so that word is given less importamce

# Tokanisation of documents
In this section, we will represent our data as a collection of words or tokens; we will also be performing word-level preprocessing tasks such as stemming. To achieve this, we will utilize the natural language toolkit, or nltk.

Stemming is a technic that reduces the inflectional forms, and sometimes derivationally related forms, of a common word to a base form. For example, the words ‘organizer’ and ‘organizing’ stems from the base word ‘organize’. So, stemming is conventionally referred to as a crude heuristic process that ‘chops’ off the ends of words, in the hope of achieving the goal correctly most of the time — this often includes the removal of derivational affixes.gives as the root of the word from derivation of that word

In [ ]:
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
porter=PorterStemmer()

In [ ]:
def tokenizer(text):
    return text.split()
tokenizer('runners like running thus they run')

['runners', 'like', 'running', 'thus', 'they', 'run']

In [ ]:
def tokenizer_stemmer(text):
    return[porter.stem(word) for word in text.split()]
tokenizer_stemmer("runners like running thus they run")

['runner', 'like', 'run', 'thu', 'they', 'run']

stopword

commomn words that always occur in a sentance like "is" "a" "and"

In [ ]:
! pip install nltk

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

stop_w=stopwords.words("english")
[w for w in tokenizer_stemmer('ship and lion in is and sleep sleeps with sleeping')[-11:]if w not in stop_w]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


['ship', 'lion', 'sleep', 'sleep', 'sleep']